### ISSUE TITLE
Signing a transaction using a newly created wallet

### ISSUE THREAD

**Issue by SusheendharVijay** [evmos/evmosjs#84]
For my use case I need to generate a random new wallet and sign an broadcast a txn using it, but I need to get some account info for it, `accountNumber` `sequence` , `pubkey` etc. To get this info this account must be used in some txn right? (I believe it's used to perfom state pruning). 

So I sending some money to the account, now I get `accountNumber` and `sequence` but `pubkey` is empty. I tried to then sign a txn using `accountNumber` `sequence` and then `pubkey` from the wallet instead of from on-chain account info. But I get this error: ```'pubKey does not match signer address evmos1kdhpt8q5vl3wg8myv680l0k0uwwvdcs25wx67a with signer index: 0: invalid pubkey'```. I'm using @hanchon 's `evmos-ts-wallet` to sign and broadcast the transaction. Really appreciate any help. Thanks!

**Comment by SusheendharVijay** [comment]
Sure thing, before that, a quick question, I need account number and sequence number to sign a transaction, how do I get those numbers for a newly created wallet? As we get no data if the address hasn't signed a transaction before. 


To reproduce you can refer to the code below, (mostly from ts-wallet npm example). For e.g a wallet I generate using `Wallet.createRandom()` : `evmos13cygv80rs7crxttxv5t79tp92dr3rttrusgydy`, I managed to send some funds to it, but while getting it's account info, I get 
```typescript
{
  sequence: 0,
  accountNumber: 2552000,
  pubkey: undefined,
  accountAddress: 'evmos13cygv80rs7crxttxv5t79tp92dr3rttrusgydy'
}
```
function I used to get the account info: 
```typescript
const getAccountInfo = async (address: string) => {
  const getInfo = provider.generateEndpointAccount(address as string);
  const res = await fetch(`${restApi}${getInfo}`);

  const data: AccountResponse = await res.json();
  const info = {
    sequence: Number(data.account.base_account.sequence),
    accountNumber: Number(data.account.base_account.account_number),
    pubkey: data.account.base_account.pub_key?.key,
    accountAddress: data.account.base_account.address,
  };

  return info;
};
```


Full code:

```typescript
import { Wallet } from "@ethersproject/wallet"
import { createMessageSend } from "@tharsis/transactions"
import { broadcast, getSender MAINNET_CHAIN, MAINNET_FEE, signTransaction } from "@hanchon/evmos-ts-wallet"


(async () => {
    const wallet = Wallet.createRandom();
// Assume there's some code to transfer some evmos to the new wallet. 
// I was successfully able to do that, checked on mintscan too. 

    // This succeeds if I transfer some evmos, 
    // but only returns account number and sequence number, the pubkey field is empty. 
    const sender = await getSender(wallet)
   
    // MAINNET_FEE for lib was too low. 
    const fee = {
      amount: "4000000000000000",
      denom: "aevmos",
      gas: "200000",
    };

    const txSimple = createMessageSend(
        MAINNET_CHAIN,
        sender,
        fee,
        '',
        {
            destinationAddress: 'evmos1pmk2r32ssqwps42y3c9d4clqlca403yd9wymgr',
            amount: '1000',
            denom: 'aevmos',
        },
    )

    const resKeplr = await signTransaction(wallet, txSimple)
    const broadcastRes = await broadcast(resKeplr)
    if (broadcastRes.tx_response.code === 0) {
        console.log('Success')
    } else {
        console.log('Error')
    }
})()```

**Comment by SusheendharVijay** [comment]
If you can show me correct the way to just spin a new wallet on the go, and then use it sign a transaction that would solve my use case.

**Comment by hanchon** [comment]
The way it works is: you must send coins to an address before using it. Sending coins registers in the blockchain the address and it will return something like this:
```
{
  sequence: 0,
  accountNumber: 2552000,
  pubkey: undefined,
  accountAddress: 'evmos13cygv80rs7crxttxv5t79tp92dr3rttrusgydy'
}
```
It makes sense that the account is not registered before receiving some coins because if you have no coins, you can not pay the fee to send a transaction.

The pubkey problem is when you didn't send any transaction yet, that's because all cosmos chains need a transaction signed by the wallet to be able to generate the pubkey (used while validating the transaction) and after getting that value the node stores it in the blockchain.

The getSender function in the `evmos-ts-wallet` takes care of the pubkey issue: https://github.com/hanchon-live/evmos-ts-wallet/blob/main/src/signer.ts#L102

Signing a `generate_pubkey` string and using that signature the deduce the wallet's pubkey:
```ts
export async function generatePubkey(wallet: Wallet) {
  // Sign the personal message `generate_pubkey` and generate the pubkey from that signature
  const signature = await wallet.signMessage('generate_pubkey')
  return signatureToPubkey(
    signature,
    Buffer.from([
      50, 215, 18, 245, 169, 63, 252, 16, 225, 169, 71, 95, 254, 165, 146, 216,
      40, 162, 115, 78, 147, 125, 80, 182, 25, 69, 136, 250, 65, 200, 94, 178,
    ]),
  )
}
```

I'm using this method instead of converting the `Wallet` pubkey directly, because when you are interacting with metamask you need to ask the user to sign the message in order to get the pubkey (the same as we are doing here).

The only thing that you are missing in your `getAccountInfo` function calling something like the `generatePubkey` function that I linked here in case the pubkey value is empty/undefined

This is the code that I use in https://evmos.me to get the pubkey from a metamask wallet:
```ts
import { signatureToPubkey } from '@hanchon/signature-to-pubkey'


export async function generatePubkeyFromSignature(wallet: string) {
  const signature = await window.ethereum.request({
    method: 'personal_sign',
    params: [wallet, 'generate_pubkey'],
  })
  const message = Buffer.from([
    50, 215, 18, 245, 169, 63, 252, 16, 225, 169, 71, 95, 254, 165, 146, 216,
    40, 162, 115, 78, 147, 125, 80, 182, 25, 69, 136, 250, 65, 200, 94, 178,
  ])

  return signatureToPubkey(signature, message)
}
```

**Comment by SusheendharVijay** [comment]
Just a quick question for my understanding, why does the compressed version of the `Wallet` pubkey not match the pubkey recovered from the signature?

**Comment by hanchon** [comment]
I don't really know how the `Wallet` pubkey is enconded, the error is probably just a different encoding from the one that we are using.
The `signatureToPubkey` function is returning `Buffer.from(senderPubKey).toString("base64");`
